//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.09 at 06:00:35 PM PDT 
//


package com.sijiang.addressbook.webservice_config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="areacode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="linenumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "firstname",
    "lastname",
    "areacode",
    "prefix",
    "linenumber",
    "countryCode"
})
@XmlRootElement(name = "AddPhoneNumberRequest", namespace="http://addressbook.com/add_phone_number")
public class AddPhoneNumberRequest {

    @XmlElement(required = true, namespace="http://addressbook.com/add_phone_number")
    protected String firstname;
    @XmlElement(required = true, namespace="http://addressbook.com/add_phone_number")
    protected String lastname;
    @XmlElement(required = true, namespace="http://addressbook.com/add_phone_number")
    protected int areacode;
    @XmlElement(required = true, namespace="http://addressbook.com/add_phone_number")
    protected int prefix;
    @XmlElement(required = true, namespace="http://addressbook.com/add_phone_number")
    protected int linenumber;
    @XmlElement(required = false, namespace="http://addressbook.com/add_phone_number")
    protected Integer countryCode;

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the areacode property.
     * 
     */
    public int getAreacode() {
        return areacode;
    }

    /**
     * Sets the value of the areacode property.
     * 
     */
    public void setAreacode(int value) {
        this.areacode = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     */
    public int getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     */
    public void setPrefix(int value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the linenumber property.
     * 
     */
    public int getLinenumber() {
        return linenumber;
    }

    /**
     * Sets the value of the linenumber property.
     * 
     */
    public void setLinenumber(int value) {
        this.linenumber = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCountryCode(Integer value) {
        this.countryCode = value;
    }

}
