//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.26 at 06:52:38 PM PDT 
//


package com.sijiang.addressbook.webservice_config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FindPersonStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Person" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PhoneNumber" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="countrycode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="areacode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="linenumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Address" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="streetname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="postalcode" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="addresstype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "findPersonStatus",
    "person"
})
@XmlRootElement(name = "FindPersonResponse")
public class FindPersonResponse {

    @XmlElement(name = "FindPersonStatus", required = true)
    protected String findPersonStatus;
    @XmlElement(name = "Person")
    protected List<FindPersonResponse.Person> person;

    /**
     * Gets the value of the findPersonStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFindPersonStatus() {
        return findPersonStatus;
    }

    /**
     * Sets the value of the findPersonStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFindPersonStatus(String value) {
        this.findPersonStatus = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the person property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FindPersonResponse.Person }
     * 
     * 
     */
    public List<FindPersonResponse.Person> getPerson() {
        if (person == null) {
            person = new ArrayList<FindPersonResponse.Person>();
        }
        return this.person;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="age" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PhoneNumber" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="countrycode" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="areacode" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="linenumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="Address" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="streetname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="postalcode" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="addresstype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "age",
        "firstname",
        "lastname",
        "username",
        "phoneNumber",
        "email",
        "address"
    })
    public static class Person {

        protected int age;
        @XmlElement(required = true)
        protected String firstname;
        @XmlElement(required = true)
        protected String lastname;
        @XmlElement(required = true)
        protected String username;
        @XmlElement(name = "PhoneNumber")
        protected List<FindPersonResponse.Person.PhoneNumber> phoneNumber;
        @XmlElement(name = "Email")
        protected List<String> email;
        @XmlElement(name = "Address")
        protected List<FindPersonResponse.Person.Address> address;

        /**
         * Gets the value of the age property.
         * 
         */
        public int getAge() {
            return age;
        }

        /**
         * Sets the value of the age property.
         * 
         */
        public void setAge(int value) {
            this.age = value;
        }

        /**
         * Gets the value of the firstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstname() {
            return firstname;
        }

        /**
         * Sets the value of the firstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstname(String value) {
            this.firstname = value;
        }

        /**
         * Gets the value of the lastname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastname() {
            return lastname;
        }

        /**
         * Sets the value of the lastname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastname(String value) {
            this.lastname = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the phoneNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the phoneNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPhoneNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FindPersonResponse.Person.PhoneNumber }
         * 
         * 
         */
        public List<FindPersonResponse.Person.PhoneNumber> getPhoneNumber() {
            if (phoneNumber == null) {
                phoneNumber = new ArrayList<FindPersonResponse.Person.PhoneNumber>();
            }
            return this.phoneNumber;
        }

        /**
         * Gets the value of the email property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the email property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEmail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getEmail() {
            if (email == null) {
                email = new ArrayList<String>();
            }
            return this.email;
        }

        /**
         * Gets the value of the address property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the address property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAddress().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FindPersonResponse.Person.Address }
         * 
         * 
         */
        public List<FindPersonResponse.Person.Address> getAddress() {
            if (address == null) {
                address = new ArrayList<FindPersonResponse.Person.Address>();
            }
            return this.address;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="streetname" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="postalcode" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="addresstype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "streetname",
            "city",
            "country",
            "postalcode",
            "addresstype"
        })
        public static class Address {

            @XmlElement(required = true)
            protected String streetname;
            @XmlElement(required = true)
            protected String city;
            @XmlElement(required = true)
            protected String country;
            protected int postalcode;
            @XmlElement(required = true)
            protected String addresstype;

            /**
             * Gets the value of the streetname property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreetname() {
                return streetname;
            }

            /**
             * Sets the value of the streetname property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreetname(String value) {
                this.streetname = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCity(String value) {
                this.city = value;
            }

            /**
             * Gets the value of the country property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCountry() {
                return country;
            }

            /**
             * Sets the value of the country property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCountry(String value) {
                this.country = value;
            }

            /**
             * Gets the value of the postalcode property.
             * 
             */
            public int getPostalcode() {
                return postalcode;
            }

            /**
             * Sets the value of the postalcode property.
             * 
             */
            public void setPostalcode(int value) {
                this.postalcode = value;
            }

            /**
             * Gets the value of the addresstype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddresstype() {
                return addresstype;
            }

            /**
             * Sets the value of the addresstype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddresstype(String value) {
                this.addresstype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="countrycode" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="areacode" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="prefix" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="linenumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "countrycode",
            "areacode",
            "prefix",
            "linenumber"
        })
        public static class PhoneNumber {

            protected int countrycode;
            protected int areacode;
            protected int prefix;
            protected int linenumber;

            /**
             * Gets the value of the countrycode property.
             * 
             */
            public int getCountrycode() {
                return countrycode;
            }

            /**
             * Sets the value of the countrycode property.
             * 
             */
            public void setCountrycode(int i) {
                this.countrycode = i;
            }

            /**
             * Gets the value of the areacode property.
             * 
             */
            public int getAreacode() {
                return areacode;
            }

            /**
             * Sets the value of the areacode property.
             * 
             */
            public void setAreacode(int i) {
                this.areacode = i;
            }

            /**
             * Gets the value of the prefix property.
             * 
             */
            public int getPrefix() {
                return prefix;
            }

            /**
             * Sets the value of the prefix property.
             * 
             */
            public void setPrefix(int i) {
                this.prefix = i;
            }

            /**
             * Gets the value of the linenumber property.
             * 
             */
            public int getLinenumber() {
                return linenumber;
            }

            /**
             * Sets the value of the linenumber property.
             * 
             */
            public void setLinenumber(int i) {
                this.linenumber = i;
            }

        }

    }

}
