//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.30 at 09:41:26 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.addressbook.com/open_account")
package com.addressbook.open_account;
